import type { Metadata } from 'next';
import './globals.css';
import Header from './components/Header';
import { Nunito, Poppins } from 'next/font/google';
import Footer from './components/Footer';

const nunito = Nunito({
  variable: '--font-nunito',
  weight: ['400', '700', '900'], // Regular, Bold, Black
  subsets: ['latin'],
  display: 'swap',
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '700'], // Regular, Bold
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fr'>
      <body className={`${nunito.variable} ${poppins.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
